import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';

function Home() {
  return (
    <div>
      <Head>
        <title>Nextflix</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://assets.nflxext.com/ffe/siteui/common/icons/nficon2016.ico"
        />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      </Head>
      <Container>
        <Image src="/netflix-logo.svg" width={207} height={55} />
      </Container>
    </div>
  );
}

export default Home;

const Container = styled.main`
  display: flex;
  justify-content: center;
  align-items: center;

  width: 100%;
  height: 100vh;
`;
